import { Message, World } from '@weave/types'

// In-memory data store (in production, this would be a database)
export const worlds: World[] = [
  {
    id: '1',
    name: '龙与地下城',
    description: '经典奇幻冒险世界',
    channels: [
      {
        id: '1',
        name: '世界公告',
        type: 'announcement',
        readonly: true,
        description: '重要的世界信息和公告',
      },
      {
        id: '2',
        name: '规则与传说',
        type: 'rules',
        readonly: true,
        description: '世界观、核心规则',
      },
      {
        id: '4',
        name: '场外闲聊',
        type: 'ooc',
        description: '游戏外的自由交流',
      },
      {
        id: '5',
        name: '场景-酒馆相遇',
        type: 'ic',
        description: '故事开始的地方',
      },
      {
        id: '6',
        name: '场景-深入龙穴',
        type: 'ic',
        description: '危险的冒险场景',
      },
    ],
    members: [],
    state: {
      world_info: {
        name: '龙与地下城',
        description: '一个充满魔法与冒险的奇幻世界',
        genre: 'fantasy',
        themes: ['冒险', '友谊', '正义', '魔法'],
        current_time: '1372年，夏末时节，傍晚',
        weather: '晴朗，微风',
      },
      characters: {
        'char-1': {
          id: 'char-1',
          name: '阿尔萨斯',
          class: '圣骑士',
          hp: 85,
          maxHp: 100,
          location: '酒馆',
          inventory: ['圣光之剑', '治疗药水', '铁甲'],
          relationships: {
            'char-2': {
              type: 'friend',
              strength: 75,
              history: ['一起开始冒险', '在哥布林洞穴中互相救助'],
              last_updated: new Date('2024-01-15T20:00:00Z'),
            },
          },
          personal_goals: ['寻找失踪的导师', '净化被诅咒的圣地'],
          known_lore: ['lore-1', 'lore-2'],
          secrets: ['曾经怀疑过自己的信仰'],
        },
        'char-2': {
          id: 'char-2',
          name: '梅林',
          class: '法师',
          hp: 60,
          maxHp: 80,
          location: '酒馆',
          inventory: ['法杖', '魔法书'],
          relationships: {
            'char-1': {
              type: 'friend',
              strength: 70,
              history: ['共同的冒险开始'],
              last_updated: new Date('2024-01-15T20:00:00Z'),
            },
          },
          personal_goals: ['掌握古代魔法', '寻找魔法学院的真相'],
          known_lore: ['lore-1', 'lore-3'],
          secrets: ['家族有黑魔法师的血统'],
        },
      },
      key_events_log: [
        {
          id: 'event-1',
          timestamp: new Date('2024-01-15T19:00:00Z'),
          type: 'story',
          title: '冒险开始',
          description: '冒险者们在酒馆中首次相遇',
          participants: ['char-1', 'char-2'],
          location: '酒馆',
          consequences: ['形成了初步的伙伴关系'],
          importance: 'high',
        },
        {
          id: 'event-2',
          timestamp: new Date('2024-01-15T19:30:00Z'),
          type: 'exploration',
          title: '发现古老遗迹',
          description: '在酒保的指引下，得知了附近古老遗迹的消息',
          participants: ['char-1', 'char-2', 'npc-1'],
          location: '酒馆',
          consequences: ['获得了第一个探索目标'],
          importance: 'medium',
        },
      ],
      npc_status: {
        'npc-1': {
          id: 'npc-1',
          name: '酒保托尼',
          description: '一个友善的矮人酒保，对当地传说了如指掌',
          current_location: '酒馆',
          personality_traits: ['友善', '健谈', '记忆力好', '乐于助人'],
          relationships: {
            'char-1': {
              type: 'acquaintance',
              strength: 60,
              history: ['第一次见面，印象良好'],
              last_updated: new Date('2024-01-15T20:00:00Z'),
            },
            'char-2': {
              type: 'acquaintance',
              strength: 55,
              history: ['简单交流'],
              last_updated: new Date('2024-01-15T20:00:00Z'),
            },
          },
          knowledge: ['当地传说', '附近地理', '冒险者的故事'],
          goals: ['经营好酒馆', '帮助冒险者'],
          secrets: ['知道附近遗迹的真正危险'],
          last_interaction: new Date('2024-01-15T20:05:00Z'),
          disposition: 'friendly',
        },
        'npc-2': {
          id: 'npc-2',
          name: '守卫队长马库斯',
          description: '镇子的守卫队长，负责维护秩序',
          current_location: '镇中心',
          personality_traits: ['严肃', '负责', '多疑', '正义'],
          relationships: {},
          knowledge: ['镇子安全', '法律条文', '可疑人员'],
          goals: ['保护镇民安全', '维护法律秩序'],
          secrets: ['担心即将到来的威胁'],
          last_interaction: new Date('2024-01-15T18:00:00Z'),
          disposition: 'neutral',
        },
      },
      locations: {
        'loc-1': {
          id: 'loc-1',
          name: '金麦酒馆',
          description: '镇上最受欢迎的酒馆，总是充满了冒险者和当地人',
          type: 'building',
          connected_locations: ['loc-2', 'loc-3'],
          notable_features: ['温暖的壁炉', '美味的炖肉', '热情的氛围'],
          current_occupants: ['char-1', 'char-2', 'npc-1'],
          hidden_secrets: ['地下室有通往古老下水道的密道'],
          danger_level: 1,
        },
        'loc-2': {
          id: 'loc-2',
          name: '绿谷镇中心',
          description: '小镇的中心广场，有一座古老的喷泉',
          type: 'town',
          connected_locations: ['loc-1', 'loc-4', 'loc-5'],
          notable_features: ['古老喷泉', '集市摊位', '公告板'],
          current_occupants: ['npc-2'],
          hidden_secrets: [],
          danger_level: 0,
        },
      },
      items: {
        'item-1': {
          id: 'item-1',
          name: '圣光之剑',
          description: '散发着温暖光芒的神圣武器',
          type: 'weapon',
          properties: { damage: '1d8+2', special: '对邪恶生物额外伤害' },
          location: 'char-1',
          owner: 'char-1',
        },
        'item-2': {
          id: 'item-2',
          name: '古老的地图',
          description: '标记着遗迹位置的褪色地图',
          type: 'key_item',
          properties: { reveals: '古老遗迹的入口' },
          location: 'loc-1',
        },
      },
      active_plots: [
        {
          id: 'plot-1',
          title: '古老遗迹的秘密',
          description: '探索酒保提到的神秘遗迹，发现其中隐藏的秘密',
          status: 'active',
          participants: ['char-1', 'char-2'],
          key_events: ['event-2'],
          next_steps: ['获取更多关于遗迹的信息', '准备探索装备'],
          importance: 'main',
        },
      ],
      rules: [
        {
          id: 'rule-1',
          name: '基础战斗规则',
          description: '角色进行攻击时的基本规则',
          category: 'combat',
          conditions: ['角色发起攻击动作'],
          effects: ['投掷d20+能力修正', '对比目标AC'],
          examples: ['阿尔萨斯攻击哥布林：投掷1d20+5，目标AC为12'],
        },
      ],
      lore: [
        {
          id: 'lore-1',
          title: '绿谷镇的历史',
          content:
            '绿谷镇建立在古老精灵文明的遗址上，因此时常有神秘事件发生...',
          category: 'history',
          tags: ['绿谷镇', '精灵', '古代'],
          related_entries: ['lore-2'],
          access_level: 'public',
        },
        {
          id: 'lore-2',
          title: '失落的精灵遗迹',
          content: '传说中的精灵遗迹位于镇子北方的森林深处，内有古老的魔法...',
          category: 'geography',
          tags: ['遗迹', '精灵', '魔法'],
          related_entries: ['lore-1'],
          access_level: 'player_discovered',
        },
        {
          id: 'lore-3',
          title: '魔法的起源',
          content: '关于这个世界魔法力量来源的古老理论...',
          category: 'magic',
          tags: ['魔法', '理论', '起源'],
          related_entries: [],
          access_level: 'gm_only',
        },
      ],
    },
  },
  {
    id: '2',
    name: '赛博朋克2077',
    description: '未来科幻世界',
    channels: [
      { id: '7', name: '世界公告', type: 'announcement', readonly: true },
      { id: '8', name: '规则与传说', type: 'rules', readonly: true },
      { id: '10', name: '场外闲聊', type: 'ooc' },
      { id: '11', name: '场景-夜之城', type: 'ic' },
    ],
    members: [],
    state: {
      world_info: {
        name: '赛博朋克2077',
        description: '一个充满未来科技与阴谋的世界',
        genre: 'cyberpunk',
        themes: ['科技', '反叛', '生存', '人性'],
        current_time: '2077年12月，深夜',
        weather: '酸雨，霓虹灯闪烁',
      },
      characters: {
        'char-3': {
          id: 'char-3',
          name: 'V',
          class: '赏金猎人',
          hp: 120,
          maxHp: 150,
          location: '夜之城',
          inventory: ['霰弹枪', '黑客工具', '增强义体'],
          relationships: {},
          personal_goals: ['找到救命的芯片', '在夜之城生存下去'],
          known_lore: [],
          secrets: ['脑中植入了神秘芯片'],
        },
      },
      key_events_log: [],
      npc_status: {},
      locations: {},
      items: {},
      active_plots: [],
      rules: [],
      lore: [],
    },
  },
  {
    id: '3',
    name: '克苏鲁的呼唤',
    description: '恐怖神秘世界',
    channels: [
      { id: '12', name: '世界公告', type: 'announcement', readonly: true },
      { id: '13', name: '规则与传说', type: 'rules', readonly: true },
      { id: '15', name: '场外闲聊', type: 'ooc' },
      { id: '16', name: '场景-阿卡姆镇', type: 'ic' },
    ],
    members: [],
    state: {
      world_info: {
        name: '克苏鲁的呼唤',
        description: '恐怖神秘世界',
        genre: 'horror',
        themes: ['恐怖', '神秘', '调查', '疯狂'],
        current_time: '1925年，秋季，午夜',
        weather: '浓雾弥漫，异常寒冷',
      },
      characters: {},
      key_events_log: [],
      npc_status: {},
      locations: {},
      items: {},
      active_plots: [],
      rules: [],
      lore: [],
    },
  },
]

export const messages: { [channelId: string]: Message[] } = {
  '1': [
    {
      id: '1',
      channelId: '1',
      worldId: '1',
      authorId: 'system',
      authorName: '系统',
      content: '欢迎来到龙与地下城世界！请先在 #角色创建 频道创建你的角色。',
      timestamp: new Date('2024-01-15T10:00:00Z'),
      type: 'system',
    },
    {
      id: '2',
      channelId: '1',
      worldId: '1',
      authorId: 'gm1',
      authorName: '游戏主持人',
      content: '今晚的冒险将在酒馆开始，请所有玩家准备好你们的角色！',
      timestamp: new Date('2024-01-15T14:30:00Z'),
      type: 'user',
    },
  ],
  '5': [
    {
      id: '3',
      channelId: '5',
      worldId: '1',
      authorId: 'gm1',
      authorName: '游戏主持人',
      content:
        '你们进入了一间温暖的酒馆，里面充满了烟草和啤酒的香味。酒保是一个友善的矮人，正在擦拭着酒杯。',
      timestamp: new Date('2024-01-15T20:00:00Z'),
      type: 'user',
    },
    {
      id: '4',
      channelId: '5',
      worldId: '1',
      authorId: 'p1',
      authorName: '龙骑士玩家',
      characterName: '阿尔萨斯',
      content: '我走向酒保，点了一杯麦酒，同时观察着酒馆里的其他客人。',
      timestamp: new Date('2024-01-15T20:05:00Z'),
      type: 'user',
    },
    {
      id: '5',
      channelId: '5',
      worldId: '1',
      authorId: 'p2',
      authorName: '法师玩家',
      characterName: '梅林',
      content:
        '我在角落找了个安静的座位，拿出魔法书假装阅读，实际上在暗中观察酒馆里的其他人。',
      timestamp: new Date('2024-01-15T20:07:00Z'),
      type: 'user',
    },
    {
      id: '6',
      channelId: '5',
      worldId: '1',
      authorId: 'p1',
      authorName: '龙骑司玩家',
      characterName: '阿尔萨斯',
      content:
        '我向酒保询问："最近镇上有什么有趣的事情发生吗？听说北边的森林里有些不寻常的动静？"',
      timestamp: new Date('2024-01-15T20:10:00Z'),
      type: 'user',
    },
    {
      id: '7',
      channelId: '5',
      worldId: '1',
      authorId: 'p2',
      authorName: '法师玩家',
      characterName: '梅林',
      content:
        '听到阿尔萨斯的问话，我竖起耳朵仔细聆听，同时准备好随时加入对话。',
      timestamp: new Date('2024-01-15T20:12:00Z'),
      type: 'user',
    },
  ],
}
